# Generated by Django 4.1.10 on 2023-11-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=100)),
                ("descriere", models.TextField()),
                ("specificatii", models.TextField()),
                ("pret", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stoc", models.PositiveIntegerField()),
                ("furnizor", models.CharField(max_length=100)),
                ("modalitate_de_livrare", models.CharField(max_length=100)),
                ("categorie", models.CharField(max_length=100)),
            ],
        ),
    ]
