# Generated by Django 4.1.10 on 2023-12-07 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("proiect", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
