# Generated by Django 4.1.10 on 2024-01-10 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=100)),
                ("descriere", models.TextField()),
                ("specificatii", models.TextField()),
                ("pret", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stoc", models.PositiveIntegerField()),
                ("furnizor", models.CharField(max_length=100)),
                ("modalitate_de_livrare", models.CharField(max_length=100)),
                ("categorie", models.CharField(max_length=100)),
                (
                    "carted_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cart_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "favorited_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favorite_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
