# Generated by Django 4.1.10 on 2024-01-10 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hello_world", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="carted_byy",
            field=models.ManyToManyField(
                blank=True, related_name="cartt_products", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
